version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: n8n-postgres
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - pg_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgres
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n
      # Habilita os nodos customizados
      N8N_CUSTOM_EXTENSIONS: "/home/node/.n8n/custom"
    volumes:
      - ./nodes:/home/node/.n8n/custom
    depends_on:
      - postgres

volumes:
  pg_data:
